#!/bin/sh
alias aliases='nvim ~/.aliases.sh'
alias c='clear'
alias dots='nvim ~/.dotfiles.dots'
alias e='exit'
alias ggh='cd ~/code/github'
alias gp='cd "$(cat ~/.current_project)"'
alias kittyrc='nvim ~/.config/kitty/kitty.conf'
alias l='eza -l'
alias lh='eza -l -a'
alias ls='eza -l'
alias reload='unalias -a && . ~/.aliases.sh'
alias rimraf='rm -rf'
alias sc='pwd > ~/.current_project'
alias v='nvim'
alias vi='nvim'
alias vim='nvim'
alias vimrc='nvim ~/.config/nvim/init.lua'
